# Generated by Django 6.0.2 on 2026-02-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_businesshours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshours',
            options={'verbose_name_plural': 'Business Hours'},
        ),
        migrations.AddField(
            model_name='businesshours',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
