# Generated by Django 6.0.2 on 2026-02-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='email',
            field=models.EmailField(default='admin@fadeblade.com', max_length=254),
            preserve_default=False,
        ),
    ]
