# Generated by Django 6.0.2 on 2026-02-27 20:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
